#!/usr/bin/with-contenv bash

# Ensure we have a /config folder
[ ! -d /config/cache ] && \
	mkdir /config/cache

# Check for presence of settings files, copy defaults if necessary
[ ! -f /config/proxysettings.json ] && \
	cp /defaults/proxysettings.json /config

[ ! -f /config/advancedsettings.json ] && \
	cp /defaults/advancedsettings.json /config

# Check for variable YAP_GIT_BRANCH and use that instead of `master` if it exists.
if [[ $YAP_GIT_BRANCH && {$YAP_GIT_BRANCH-x} ]]; then
	GIT_BRANCH=$YAP_GIT_BRANCH
else
	GIT_BRANCH=master
fi

# install app 
[[ ! -d "/app/sstvproxy/.git" ]] && \
	echo "Installing sstvProxy from branch: $GIT_BRANCH"
	git clone --branch $GIT_BRANCH https://github.com/vorghahn/sstvProxy.git /app/sstvproxy

# Get docker IP address and replace it in proxysettings.json
IPADDR=`ip addr | grep 'state UP' -A2 | tail -n1 | awk '{print $2}' | cut -f1  -d'/'`
sed -ri "s/([\"']ip[\"']:)[^\"']*([\"'])[^\"']*([\"'])/\1 \2${IPADDR}\3/g" /config/proxysettings.json

# Substitute proxysettings.json values with environment variables passed to container

[[ $YAP_SERVICE && ${YAP_SERVICE-x} ]] && \
	sed -ri "s/([\"']service[\"']:)[^\"']*([\"'])[^\"']*([\"'])/\1 \2${YAP_SERVICE}\3/g" /config/proxysettings.json

[[ $YAP_USERNAME && ${YAP_USERNAME-x} ]] && \
	sed -ri "s/([\"']username[\"']:)[^\"']*([\"'])[^\"']*([\"'])/\1 \2${YAP_USERNAME}\3/g" /config/proxysettings.json

[[ $YAP_PASSWORD && ${YAP_PASSWORD-x} ]] && \
	sed -ri "s/([\"']password[\"']:)[^\"']*([\"'])[^\"']*([\"'])/\1 \2${YAP_PASSWORD}\3/g" /config/proxysettings.json

[[ $YAP_SERVER && ${YAP_SERVER-x} ]] && \
	sed -ri "s/([\"']server[\"']:)[^\"']*([\"'])[^\"']*([\"'])/\1 \2${YAP_SERVER}\3/g" /config/proxysettings.json

[[ $YAP_QUALITY && ${YAP_QUALITY-x} ]] && \
	sed -ri "s/([\"']quality[\"']:)[^0-9]*[1-3]/\1 ${YAP_QUALITY}/g" /config/proxysettings.json

[[ $YAP_STREAM && ${YAP_STREAM-x} ]] && \
	sed -ri "s/([\"']stream[\"']:)[^\"']*([\"'])[^\"']*([\"'])/\1 \2${YAP_STREAM}\3/g" /config/proxysettings.json

[[ $YAP_EXTERNALIP && ${YAP_EXTERNALIP-x} ]] && \
	sed -ri "s/([\"']externalip[\"']:)[^\"']*([\"'])[^\"']*([\"'])/\1 \2${YAP_EXTERNALIP}\3/g" /config/proxysettings.json

[[ $YAP_KODIPORT && ${YAP_KODIPORT-x} ]] && \
	sed -ri "s/([\"']kodiport[\"']:)[^0-9]*[0-9]{2,5}/\1 ${YAP_KODIPORT}/g" /config/proxysettings.json

# Create symlinks to settings files in /app/sstvproxy
ln -sf /config/proxysettings.json /app/sstvproxy/proxysettings.json
ln -sf /config/advancedsettings.json /app/sstvproxy/advancedsettings.json
ln -sf /config/cache /app/sstvproxy/cache

# permissions
chown abc:abc -R \
	/app/sstvproxy \
	/config
